# DJ Set Song Recognition (Proof of Concept)

Given a music library and a recorded DJ set exclusively containing songs from that music library, this notebook attempts to identify which songs are playing at each time in the DJ set.

The matter is complicated by the fact that at a given time in my sets I'm usually playing two songs at the same time.

Initial results of this experiment, showing modest success (and a lot of false positives) follow the code:

## Load useful libraries

In [1]:
import librosa

import multiprocessing
import os
import glob

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.spatial.distance import cosine

from pyspark.sql import SparkSession
from pyspark.conf import SparkConf
import pyspark.sql.functions as F
from pyspark.sql import Window
from pyspark.sql.types import FloatType, ArrayType, StringType

## User settings

In [2]:
output_directory = 'output'

# location of tracks to analyze for building the track feature database
playlist_parquet = '../database/music/output/playlist.parquet'

# location of the recorded DJ set which we want to analyze
filename_show = '/home/emily/Desktop/projects/dj/song_recognition/data/partial-goth-set.mp3'

## Load track file paths from the playlist file

This playlist lists the tracks used in a DJ performance. However, it does not specify the order in which I play them or how I blend tracks together (why we need this software in the first place!).

In [3]:
df_playlist = pd.read_parquet(playlist_parquet)

In [4]:
df_playlist.head(5)

     id                                               path
0  4822  /media/emily/DJ_Backup/Tracks - A/2025-05-18/7...
1  1443  /media/emily/DJ_Backup/Tracks - A/03 - Can I P...
2  4976  /media/emily/DJ_Backup/Tracks - A/2025-10-25/0...
3  2149  /media/emily/DJ_Backup/Tracks - A/2022-11-07/0...
4    91  /media/emily/DJ_Backup/Tracks - A/Front 242 - ...

In [5]:
df_playlist['path'][0:5].values

array(['/media/emily/DJ_Backup/Tracks - A/2025-05-18/76 - Lunch Box_PN.mp3',
       '/media/emily/DJ_Backup/Tracks - A/03 - Can I Play with Madness (2015 Remaster)_pn.mp3',
       '/media/emily/DJ_Backup/Tracks - A/2025-10-25/01 - Military Fashion Show (Club Hit)_PN.mp3',
       '/media/emily/DJ_Backup/Tracks - A/2022-11-07/01 - Burn_pn.mp3',
       '/media/emily/DJ_Backup/Tracks - A/Front 242 - DJ Hell - Electronicbody-Housemusic CD2 - Headhunter_pn.mp3'],
      dtype=object)

## Define a function that produces a chromagram for a track for a specific octave

By performing this analysis one octave at a time and then appending the results together (later), we obtain a chromagram vector that covers every note on the piano seperately per time step.

In [6]:
def process_octave(y, sr, octave_number, hop_length = 512 * 200, lowest_pitch = 16.35):  # get a more precise number for C0
    chromagram = librosa.feature.chroma_cens(
        y = y,
        sr = sr,
        fmin = lowest_pitch * (octave_number + 1),
        n_octaves = 1,
        hop_length = hop_length,
    )
    return chromagram

## Define function enabling parallelized track analysis

In [7]:
def process_song_from_song_library(filename, track_id):
    y_tick_labels = librosa.key_to_notes('C:major')  # we compute this every time for now, neither efficient nor too costly

    # there is a file not found error I need to debug later
    try:
        y, sr = librosa.load(filename)
    except:
        return None
    
    y_harmonic, y_percussive = librosa.effects.hpss(y)
    results_list = []
    for octave_number in range(0, 9):
        chromagram = process_octave(y_harmonic, sr, octave_number)
        df = pd.DataFrame(chromagram.T)
        df.columns = [x + str(octave_number) for x in y_tick_labels]
        results_list.append(df)
    df_all_octaves = pd.concat(results_list, axis = 1)
    df_all_octaves['id'] = track_id
    return df_all_octaves

## Mathematically process song library to extract features

In [8]:
args_list = []
for i, row in df_playlist.iterrows():
    args_list.append((row['path'], row['id']))

with multiprocessing.Pool(processes = 50) as pool:
    results = pool.starmap(process_song_from_song_library, args_list)

/tmp/ipykernel_1468368/3171468248.py:6: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(filename)
/home/emily/venvs/ml/lib/python3.10/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_1468368/3171468248.py:6: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(filename)
/home/emily/venvs/ml/lib/python3.10/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_1468368/3171468248.py:6: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(filename)
/home/emily/venvs/ml/lib/python3.10/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_1468368/3171468248.py:6: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(filename)
/home/emily/venvs/ml/lib/python3.10/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_1468368/3171468248.py:6: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(filename)
/home/emily/venvs/ml/lib/python3.10/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_1468368/3171468248.py:6: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(filename)
/home/emily/venvs/ml/lib/python3.10/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_1468368/3171468248.py:6: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(filename)
/home/emily/venvs/ml/lib/python3.10/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_1468368/3171468248.py:6: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(filename)
/home/emily/venvs/ml/lib/python3.10/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

## Assemble song library feature vectors into a DataFrame

In [9]:
df = pd.concat(results, ignore_index = True)

In [10]:
df.head(3)

,C0,C♯0,D0,D♯0,E0,F0,F♯0,G0,G♯0,A0,...,D♯8,E8,F8,F♯8,G8,G♯8,A8,A♯8,B8,id
0,0.344815,0.112089,0.136367,0.172484,0.142443,0.205490,0.174831,0.343460,0.368679,0.270560,...,0.259114,0.191983,0.196706,0.272766,0.181645,0.354552,0.456288,0.247082,0.280853,4822
1,0.344740,0.110633,0.134253,0.167168,0.139185,0.202820,0.173641,0.340443,0.365030,0.277271,...,0.262891,0.193481,0.197752,0.273631,0.182349,0.353875,0.464535,0.242827,0.278242,4822
2,0.344576,0.109610,0.132323,0.162348,0.136196,0.200319,0.172394,0.337547,0.361117,0.283469,...,0.266301,0.195185,0.198989,0.274916,0.183178,0.352304,0.471738,0.238417,0.275931,4822

## Song library QA

To Do:  Need to identify why these rows produce NaNs.

In [11]:
len(df.index)

11325

In [12]:
len(df.dropna().index)

11325

In [14]:
len(df['id'].unique())

185

## Remove rows having NaNs

To Do:  Need to identify why these rows produce NaNs.

In [15]:
df.dropna(inplace = True)

## Save song library vectors for later use

In the long run, we'd prefer using a vector database.

In [16]:
df.to_parquet(output_directory + '/song_library_vectors.parquet')

## Load song library vectors (so we can start from here next time)

In the long run, we'd prefer using a vector database.

In [17]:
pdf = pd.read_parquet(output_directory + '/song_library_vectors.parquet')

## Load recorded show and extract harmonic content

In [18]:
y_show, sr_show = librosa.load(filename_show)
y_show_harmonic, y_show_percussive = librosa.effects.hpss(y_show)

## Define function for extracting per time step features of the recorded DJ set

In [19]:
def process_show(y_harmonic, sr):
    y_tick_labels = librosa.key_to_notes('C:major')  # we compute this every time for now
    results_list = []
    for octave_number in range(0, 9):
        chromagram = process_octave(y_harmonic, sr, octave_number)
        df = pd.DataFrame(chromagram.T)
        df.columns = [x + str(octave_number) for x in y_tick_labels]
        results_list.append(df)
    df_all_octaves = pd.concat(results_list, axis = 1)
    return df_all_octaves

## Compute DJ set features per time step

In [20]:
df_show = process_show(y_show_harmonic, sr_show)

## Recorded show QA

In [21]:
len(df_show.index)

3252

In [22]:
len(df_show.dropna().index)

3252

## Save the show vectors for later use

In [23]:
df_show.to_parquet(output_directory + '/show_vectors.parquet')

## Load the previously saved show vectors

So we can start computation here after leaving it awhile:

In [24]:
df_show = pd.read_parquet(output_directory + '/show_vectors.parquet')

In [25]:
df_show

,C0,C♯0,D0,D♯0,E0,F0,F♯0,G0,G♯0,A0,...,D8,D♯8,E8,F8,F♯8,G8,G♯8,A8,A♯8,B8
0,0.253968,0.134070,0.100559,0.170141,0.078711,0.188392,0.169125,0.278568,0.326929,0.381175,...,0.116411,0.056590,0.165452,0.340058,0.501667,0.201821,0.031296,0.104000,0.191747,0.683396
1,0.257956,0.132972,0.101686,0.164569,0.080406,0.188235,0.169111,0.273880,0.322755,0.380282,...,0.114386,0.061166,0.168905,0.337733,0.506769,0.201279,0.034587,0.103490,0.189390,0.680270
2,0.262335,0.131938,0.102944,0.158705,0.081942,0.188067,0.169228,0.269436,0.319038,0.379379,...,0.113406,0.066155,0.172793,0.335800,0.511332,0.201171,0.037855,0.104126,0.187339,0.676595
3,0.267023,0.130858,0.104200,0.152562,0.083258,0.187923,0.169590,0.265212,0.315755,0.378541,...,0.113301,0.071708,0.177557,0.334321,0.515049,0.201382,0.041269,0.105584,0.185542,0.672533
4,0.271773,0.129649,0.105353,0.146150,0.084311,0.187829,0.170190,0.261190,0.312972,0.377820,...,0.113954,0.077833,0.183537,0.333481,0.517750,0.201738,0.045070,0.107742,0.184091,0.668051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3247,0.328264,0.056888,0.066818,0.072767,0.093677,0.143530,0.185510,0.233534,0.280256,0.388499,...,0.306932,0.103649,0.104618,0.232152,0.466984,0.385055,0.302564,0.235584,0.238357,0.123861
3248,0.323829,0.055678,0.065486,0.070145,0.093704,0.143534,0.184595,0.233118,0.280319,0.391364,...,0.303376,0.099480,0.093658,0.228821,0.478346,0.383913,0.299334,0.233938,0.243031,0.113282
3249,0.319502,0.054572,0.064136,0.067533,0.093732,0.143627,0.183703,0.232813,0.280812,0.394387,...,0.300581,0.095876,0.082888,0.225157,0.489586,0.382440,0.295621,0.231949,0.247500,0.102774
3250,0.315365,0.053314,0.062494,0.064685,0.093708,0.143808,0.182639,0.232464,0.281675,0.397470,...,0.298436,0.092735,0.072583,0.221250,0.500775,0.380491,0.291435,0.229690,0.251790,0.092604
3251,0.311492,0.051816,0.060331,0.061538,0.093710,0.144114,0.181309,0.231926,0.282772,0.400581,...,0.296775,0.089779,0.062951,0.217202,0.511986,0.377985,0.286638,0.227106,0.255790,0.082969

## Start a Spark session

In [26]:
conf = (
    SparkConf()
    .setAppName("MyApp")
    .set("spark.executor.memory", "70G")
    .set("spark.driver.memory", "70G")
    .set("spark.driver.maxResultSize", "70G")
)

spark = SparkSession.builder.config(conf = conf).getOrCreate()

26/03/17 12:43:06 WARN Utils: Your hostname, emily-MS-7B96 resolves to a loopback address: 127.0.1.1; using 192.168.1.99 instead (on interface eno1)
26/03/17 12:43:06 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/17 12:43:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

## Save the column names for later use

In [27]:
value_columns = df_show.columns

## Enumerate the time steps

In [28]:
df_show['timestamp'] = df_show.index

## Convert the Pandas dataframes into Spark Dataframes

In [29]:
sdf_show = (
    spark
    .createDataFrame(df_show)
    .orderBy('timestamp')
    .withColumn('array_show', F.array(*value_columns))
    .select('timestamp', 'array_show')
)

In [30]:
sdf_show.show(2)

26/03/17 12:43:15 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+---------+--------------------+
|timestamp|          array_show|
+---------+--------------------+
|        0|[0.25396835803985...|
|        1|[0.25795611739158...|
+---------+--------------------+
only showing top 2 rows

In [31]:
sdf_library = (
    spark
    .createDataFrame(pdf)
    .orderBy('id')
    .repartition('id')
    .withColumn('array_library', F.array(*value_columns))
    .select('array_library', 'id')
)

In [32]:
sdf_library.show(2)

+--------------------+----+
|       array_library|  id|
+--------------------+----+
|[0.34639683365821...|2149|
|[0.34315595030784...|2149|
+--------------------+----+
only showing top 2 rows

## Save the show and library vectors in Spark-friendly parquet format

In [33]:
sdf_show.write.mode('overwrite').parquet(output_directory + '/show_vectors_spark.parquet')

In [34]:
sdf_library.write.mode('overwrite').parquet(output_directory + '/library_vectors_spark.parquet')

26/03/17 12:43:24 WARN GarbageCollectionMetrics: To enable non-built-in garbage collector(s) List(G1 Concurrent GC), users should configure it(them) to spark.eventLog.gcMetrics.youngGenerationGarbageCollectors or spark.eventLog.gcMetrics.oldGenerationGarbageCollectors

## Clear some memory

Not sure whether this is necessary or not...

In [35]:
del(df_show)
del(pdf)

## Load the show and library vectors from the Spark-friendly parquet

So we can start here when the memory is clear:

In [36]:
sdf_show = spark.read.parquet(output_directory + '/show_vectors_spark.parquet')

In [37]:
sdf_library = spark.read.parquet(output_directory + '/library_vectors_spark.parquet')

## Combine the two dataframes with a cross join

Also preemptively repartition it.

In [92]:
sdf_cross_joined = sdf_show.crossJoin(sdf_library)

In [93]:
sdf_cross_joined.show(2)

+---------+--------------------+--------------------+---+
|timestamp|          array_show|       array_library| id|
+---------+--------------------+--------------------+---+
|     1594|[0.25094535946846...|[0.33483257889747...| 91|
|     1595|[0.25330230593681...|[0.33483257889747...| 91|
+---------+--------------------+--------------------+---+
only showing top 2 rows

## Define a user-defined function (UDF) for computing cosine similarity

Computes the cosine similarity between two vectors:

In [94]:
@F.udf(returnType=FloatType())
def compute_cosine_similarity(vector1, vector2):
    cosine_dist = cosine(np.array(vector1), np.array(vector2))
    similarity_score = 1 - cosine_dist
    return float(similarity_score)

## Compute cosine similarity for each row

In [95]:
sdf_cross_joined = (
    sdf_cross_joined
    .withColumn('cosine_similarity', compute_cosine_similarity(F.col('array_show'), F.col('array_library')))
    .drop('array_show', 'array_library')
)

In [96]:
sdf_cross_joined.show(2)

+---------+---+-----------------+
|timestamp| id|cosine_similarity|
+---------+---+-----------------+
|     1594| 91|        0.8350759|
|     1595| 91|        0.8358625|
+---------+---+-----------------+
only showing top 2 rows

## Keep only the top 25th percentile of cosine similarities

This is a simple heuristic for reducing the dataset size.

In [97]:
sdf_cross_joined.repartition(100)

DataFrame[timestamp: bigint, id: bigint, cosine_similarity: float]

In [98]:
print(sdf_cross_joined.count())

36828900

In [100]:
# compute 75th percentile
q75 = sdf_cross_joined.approxQuantile('cosine_similarity', [0.80], 0.05)

In [101]:
q75

[0.8665580749511719]

In [102]:
sdf_cross_joined = sdf_cross_joined.where(F.col('cosine_similarity') >= F.lit(q75[0]))

In [103]:
print(sdf_cross_joined.count())

26/03/18 15:06:37 WARN ExtractPythonUDFFromJoinCondition: The join condition:(compute_cosine_similarity(array_show#685, array_library#688)#1071 >= 0.8665581) of the join plan contains PythonUDF only, it will be moved out and the join plan will be turned to cross join.

7907735

## Aggregate by (timestamp, song_id)

We retain the maximum cosine similarity per (timestamp / song ID) pair:

In [104]:
sdf_cross_joined.repartition('timestamp', 'id')

sdf_agg = (
    sdf_cross_joined
    #.orderBy(F.asc('timestamp'), F.desc('cosine_similarity'))
    .groupBy('timestamp', 'id')
    .agg(
        F.max('cosine_similarity').alias('cosine_similarity'),
    )
)

In [108]:
sdf_agg = sdf_agg.orderBy('timestamp', F.desc('cosine_similarity'))

In [109]:
sdf_agg.show(5)

26/03/18 23:43:04 WARN ExtractPythonUDFFromJoinCondition: The join condition:(compute_cosine_similarity(array_show#685, array_library#688)#1071 >= 0.8665581) of the join plan contains PythonUDF only, it will be moved out and the join plan will be turned to cross join.

+---------+----+-----------------+
|timestamp|  id|cosine_similarity|
+---------+----+-----------------+
|        0|1176|       0.98020715|
|        0|1280|       0.93996507|
|        0|5241|        0.9312942|
|        0|2173|       0.90333176|
|        0|1937|        0.8942697|
+---------+----+-----------------+
only showing top 5 rows

## Record the rank per timestamp

In [110]:
sdf_agg.repartition('timestamp')

DataFrame[timestamp: bigint, id: bigint, cosine_similarity: float]

In [111]:
window_spec = Window.partitionBy('timestamp').orderBy(F.desc('cosine_similarity'))

sdf_agg_next = (
    sdf_agg
    .orderBy(F.asc('timestamp'), F.desc('cosine_similarity'))
    .withColumn('rank', F.row_number().over(window_spec))
)

In [112]:
sdf_agg_next.show(5)

26/03/18 23:50:39 WARN ExtractPythonUDFFromJoinCondition: The join condition:(compute_cosine_similarity(array_show#685, array_library#688)#1071 >= 0.8665581) of the join plan contains PythonUDF only, it will be moved out and the join plan will be turned to cross join.

+---------+----+-----------------+----+
|timestamp|  id|cosine_similarity|rank|
+---------+----+-----------------+----+
|        0|1176|       0.98020715|   1|
|        0|1280|       0.93996507|   2|
|        0|5241|        0.9312942|   3|
|        0|2173|       0.90333176|   4|
|        0|1937|        0.8942697|   5|
+---------+----+-----------------+----+
only showing top 5 rows

## Keep the top N per timestamp

In [113]:
n = 3

sdf_agg_next = sdf_agg_next.where(F.col('rank') <= 3)

In [114]:
sdf_agg_next.show(10)

26/03/18 23:56:29 WARN ExtractPythonUDFFromJoinCondition: The join condition:(compute_cosine_similarity(array_show#685, array_library#688)#1071 >= 0.8665581) of the join plan contains PythonUDF only, it will be moved out and the join plan will be turned to cross join.

+---------+----+-----------------+----+
|timestamp|  id|cosine_similarity|rank|
+---------+----+-----------------+----+
|        0|1176|       0.98020715|   1|
|        0|1280|       0.93996507|   2|
|        0|5241|        0.9312942|   3|
|        1|1176|        0.9802379|   1|
|        1|1280|       0.94038284|   2|
|        1|5241|       0.93169487|   3|
|        2|1176|        0.9803439|   1|
|        2|1280|       0.94084287|   2|
|        2|5241|       0.93215847|   3|
|        3|1176|        0.9805271|   1|
+---------+----+-----------------+----+
only showing top 10 rows

## Join to get the track names

In [115]:
df_ranked = sdf_agg_next.toPandas()

26/03/19 00:03:05 WARN ExtractPythonUDFFromJoinCondition: The join condition:(compute_cosine_similarity(array_show#685, array_library#688)#1071 >= 0.8665581) of the join plan contains PythonUDF only, it will be moved out and the join plan will be turned to cross join.

In [120]:
df_mix = (
    pd.merge(
        df_ranked,
        df_playlist,
        how = 'left',
        on = 'id',
    )
    .drop(columns = ['cosine_similarity', 'id'])
)

In [122]:
df_mix['path'] = [x.split('/')[-1].replace('.mp3', '') for x in df_mix['path']]

## Compute time in seconds

In [135]:
# TO FIX: This should be specified in the user settings and propagated through the calculations above
hop_length = 512 * 200
sr = 22050

df_mix['time'] = [x / (sr / hop_length) for x in df_mix['timestamp']]

## Pivot the DataFrame

In [136]:
df_mix_pivoted = df_mix.pivot(index='time', columns='rank', values='path')

## Display estimated results

In [142]:
pd.set_option('display.max_rows', None)
df_mix_pivoted.drop_duplicates().head(200)

rank,1,2,3
time,,,
0.000000,Billy Idol - Cyberpunk - Shock To The System_pn,3851968_Club Wedding_(Jack Rokka Remix)_PN,11 - DSM-V_PN
83.591837,Billy Idol - Cyberpunk - Shock To The System_pn,3851968_Club Wedding_(Jack Rokka Remix)_PN,01 - Epic (Radio Remix Edit)_pn
88.235828,Billy Idol - Cyberpunk - Shock To The System_pn,01 - Epic (Radio Remix Edit)_pn,3851968_Club Wedding_(Jack Rokka Remix)_PN
92.879819,Billy Idol - Cyberpunk - Shock To The System_pn,01 - Epic (Radio Remix Edit)_pn,6034307_N.W.O. (Re-Recorded)_(Original Mix)_PN
97.523810,Billy Idol - Cyberpunk - Shock To The System_pn,6034307_N.W.O. (Re-Recorded)_(Original Mix)_PN,01 - Epic (Radio Remix Edit)_pn
106.811791,6034307_N.W.O. (Re-Recorded)_(Original Mix)_PN,Billy Idol - Cyberpunk - Shock To The System_pn,01 - Epic (Radio Remix Edit)_pn
116.099773,6034307_N.W.O. (Re-Recorded)_(Original Mix)_PN,01 - Epic (Radio Remix Edit)_pn,Billy Idol - Cyberpunk - Shock To The System_pn
157.895692,6034307_N.W.O. (Re-Recorded)_(Original Mix)_PN,01 - Epic (Radio Remix Edit)_pn,Faith No More - Angel Dust - MidLife Crisis_pn
171.827664,6034307_N.W.O. (Re-Recorded)_(Original Mix)_PN,01 - Epic (Radio Remix Edit)_pn,NØXIA - Pray For Me_pn
222.911565,6034307_N.W.O. (Re-Recorded)_(Original Mix)_PN,01 - Epic (Radio Remix Edit)_pn,My Life With The Thrill Kill Kult - Confession...
236.843537,6034307_N.W.O. (Re-Recorded)_(Original Mix)_PN,01 - Marcha Funebre [Explicit]_PN,My Life With The Thrill Kill Kult - Confession...
241.487528,01 - Marcha Funebre [Explicit]_PN,6034310_Fade to Black_(Original Mix)_PN,6034307_N.W.O. (Re-Recorded)_(Original Mix)_PN
246.131519,01 - Marcha Funebre [Explicit]_PN,6034310_Fade to Black_(Original Mix)_PN,Consolidated - Another World - Electronic Body...
250.775510,01 - Marcha Funebre [Explicit]_PN,6034310_Fade to Black_(Original Mix)_PN,The Cure - Wrong Number (Euro CDS) - Wrong Num...
255.419501,01 - Marcha Funebre [Explicit]_PN,6034310_Fade to Black_(Original Mix)_PN,(Disc 2) 04 - Breaking Up The Girl (Timo Maas ...
283.283447,01 - Marcha Funebre [Explicit]_PN,(Disc 2) 04 - Breaking Up The Girl (Timo Maas ...,6034310_Fade to Black_(Original Mix)_PN
469.043084,01 - Marcha Funebre [Explicit]_PN,(Disc 2) 04 - Breaking Up The Girl (Timo Maas ...,Muse - The Resistance - MK Ultra_pn
473.687075,01 - Marcha Funebre [Explicit]_PN,5020207_Pro-test_(Original Mix)_PN,(Disc 2) 04 - Breaking Up The Girl (Timo Maas ...
482.975057,01 - Marcha Funebre [Explicit]_PN,5020207_Pro-test_(Original Mix)_PN,5255770_Time Will Destroy Everything_(Original...
487.619048,5020207_Pro-test_(Original Mix)_PN,01 - Marcha Funebre [Explicit]_PN,5255770_Time Will Destroy Everything_(Original...
492.263039,5020207_Pro-test_(Original Mix)_PN,5255770_Time Will Destroy Everything_(Original...,1002070_Mirror Saw_(Dub Mix)_PN
496.907029,5020207_Pro-test_(Original Mix)_PN,5255770_Time Will Destroy Everything_(Original...,04 - Hyperpunk_pn
501.551020,04 - Hyperpunk_pn,5020207_Pro-test_(Original Mix)_PN,5255770_Time Will Destroy Everything_(Original...
506.195011,04 - Hyperpunk_pn,5020207_Pro-test_(Original Mix)_PN,18700985_Paint it Black_(Melodic Techno Mix)_PN
510.839002,04 - Hyperpunk_pn,18700985_Paint it Black_(Melodic Techno Mix)_PN,5020207_Pro-test_(Original Mix)_PN
515.482993,04 - Hyperpunk_pn,18700985_Paint it Black_(Melodic Techno Mix)_PN,Sally Dige - Holding On - 07 No Need To Preten...
520.126984,04 - Hyperpunk_pn,01 - Welcome to Night City_pn,18700985_Paint it Black_(Melodic Techno Mix)_PN
524.770975,04 - Hyperpunk_pn,01 - Welcome to Night City_pn,Sally Dige - Holding On - 07 No Need To Preten...
599.074830,04 - Hyperpunk_pn,Sally Dige - Holding On - 07 No Need To Preten...,01 - Welcome to Night City_pn
608.362812,04 - Hyperpunk_pn,Sally Dige - Holding On - 07 No Need To Preten...,18700985_Paint it Black_(Melodic Techno Mix)_PN
626.938776,04 - Hyperpunk_pn,18700985_Paint it Black_(Melodic Techno Mix)_PN,GreenFlamez - Vertigo (Original Mix)_PN
631.582766,18700985_Paint it Black_(Melodic Techno Mix)_PN,04 - Hyperpunk_pn,GreenFlamez - Vertigo (Original Mix)_PN
636.226757,18700985_Paint it Black_(Melodic Techno Mix)_PN,GreenFlamez - Vertigo (Original Mix)_PN,1002070_Mirror Saw_(Dub Mix)_PN
650.158730,Collide - Chasing the Ghost - Ocean_pn,18700985_Paint it Black_(Melodic Techno Mix)_PN,GreenFlamez - Vertigo (Original Mix)_PN
654.802721,Collide - Chasing the Ghost - Ocean_pn,Boris Mikulic - Another World - Electronic Bod...,Collide - Chasing the Ghost - Transfer_pn
664.090703,Boris Mikulic - Another World - Electronic Bod...,Collide - Chasing the Ghost - Ocean_pn,Collide - Chasing the Ghost - Transfer_pn
678.022676,Boris Mikulic - Another World - Electronic Bod...,04 - Come Undone (Remix)_PN,Collide - Chasing the Ghost - Ocean_pn
682.666667,Boris Mikulic - Another World - Electronic Bod...,04 - Come Undone (Remix)_PN,06 - Epidemic_PN
701.242630,Boris Mikulic - Another World - Electronic Bod...,04 - Come Undone (Remix)_PN,02 - Wonderland_pn
705.886621,04 - Come Undone (Remix)_PN,02 - Wonderland_pn,06 - Epidemic_PN
710.530612,02 - Wonderland_pn,04 - Come Undone (Remix)_PN,06 - Epidemic_PN
719.818594,02 - Wonderland_pn,06 - Epidemic_PN,04 - Come Undone (Remix)_PN
729.106576,02 - Wonderland_pn,06 - Epidemic_PN,07 - Hole in the Sun (feat. COS & Conway) [Exp...
743.038549,02 - Wonderland_pn,07 - Hole in the Sun (feat. COS & Conway) [Exp...,06 - Epidemic_PN
803.410431,02 - Wonderland_pn,06 - Epidemic_PN,Collide - Chasing the Ghost - White Rabbit_pn
821.986395,02 - Wonderland_pn,Collide - Chasing the Ghost - White Rabbit_pn,06 - Epidemic_PN
835.918367,02 - Wonderland_pn,Collide - Chasing the Ghost - White Rabbit_pn,6034326_In Penetration_(Original Mix)_PN
840.562358,Collide - Chasing the Ghost - White Rabbit_pn,02 - Wonderland_pn,01 - PROPAGANDA_pn
845.206349,Collide - Chasing the Ghost - White Rabbit_pn,01 - PROPAGANDA_pn,02 - Wonderland_pn
849.850340,Collide - Chasing the Ghost - White Rabbit_pn,01 - PROPAGANDA_pn,Lake Hills - BLEAK (Original Mix)_PN
863.782313,Collide - Chasing the Ghost - White Rabbit_pn,01 - PROPAGANDA_pn,ALTIMAIT - Underwater_pn
868.426304,ALTIMAIT - Underwater_pn,Collide - Chasing the Ghost - White Rabbit_pn,01 - PROPAGANDA_pn
877.714286,ALTIMAIT - Underwater_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...,Collide - Chasing the Ghost - White Rabbit_pn
882.358277,ALTIMAIT - Underwater_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...,NØXIA - Pray For Me_pn
891.646259,ALTIMAIT - Underwater_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...,01 - Military Fashion Show (Club Hit)_PN
905.578231,ALTIMAIT - Underwater_pn,01 - Military Fashion Show (Club Hit)_PN,She Lost Kontrol - Surviving In Europe - 13 Pr...
933.442177,ALTIMAIT - Underwater_pn,01 - Military Fashion Show (Club Hit)_PN,john crozier harrison - John Crozier Harrison ...
961.306122,ALTIMAIT - Underwater_pn,john crozier harrison - John Crozier Harrison ...,01 - Military Fashion Show (Club Hit)_PN
965.950113,john crozier harrison - John Crozier Harrison ...,ALTIMAIT - Underwater_pn,01 - Military Fashion Show (Club Hit)_PN
970.594104,john crozier harrison - John Crozier Harrison ...,01 - Military Fashion Show (Club Hit)_PN,ALTIMAIT - Underwater_pn
1007.746032,john crozier harrison - John Crozier Harrison ...,01 - Military Fashion Show (Club Hit)_PN,Collide - Chasing the Ghost - White Rabbit_pn
1030.965986,john crozier harrison - John Crozier Harrison ...,01 - Military Fashion Show (Club Hit)_PN,01 - Light Up the Sky (PENGSHUi Remix)_pn
1040.253968,john crozier harrison - John Crozier Harrison ...,01 - Military Fashion Show (Club Hit)_PN,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...
1049.541950,01 - Military Fashion Show (Club Hit)_PN,john crozier harrison - John Crozier Harrison ...,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...
1054.185941,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,01 - Military Fashion Show (Club Hit)_PN,john crozier harrison - John Crozier Harrison ...
1058.829932,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,01 - Military Fashion Show (Club Hit)_PN,6034329_The Animal (Youthsad Mix)_(Original Mi...
1068.117914,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,01 - Military Fashion Show (Club Hit)_PN,Front 242 - DJ Hell - Electronicbody-Housemusi...
1072.761905,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,Front 242 - DJ Hell - Electronicbody-Housemusi...,01 - Military Fashion Show (Club Hit)_PN
1082.049887,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,Front 242 - DJ Hell - Electronicbody-Housemusi...,1002052_Shore Lined Poison_(Remix)_pn
1123.845805,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,1002052_Shore Lined Poison_(Remix)_pn,Front 242 - DJ Hell - Electronicbody-Housemusi...
1156.353741,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,Front 242 - DJ Hell - Electronicbody-Housemusi...,She Lost Kontrol - Surviving In Europe - 13 Pr...
1160.997732,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,She Lost Kontrol - Surviving In Europe - 13 Pr...,Front 242 - DJ Hell - Electronicbody-Housemusi...
1170.285714,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,She Lost Kontrol - Surviving In Europe - 13 Pr...,NØXIA - Lemon Pie_pn
1184.217687,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,She Lost Kontrol - Surviving In Europe - 13 Pr...,Phase Fatale - Anubis - 01 Hollow Flesh_pn
1188.861678,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,Phase Fatale - Anubis - 01 Hollow Flesh_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...
1193.505669,Phase Fatale - Anubis - 01 Hollow Flesh_pn,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...,She Lost Kontrol - Surviving In Europe - 13 Pr...
1198.149660,Phase Fatale - Anubis - 01 Hollow Flesh_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...,6034336_Jesus Built My Hotrod (Re-Recorded)_(O...
1212.081633,Phase Fatale - Anubis - 01 Hollow Flesh_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...,NØXIA - Lemon Pie_pn
1216.725624,Phase Fatale - Anubis - 01 Hollow Flesh_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...,NØXIA - Pray For Me_pn
1244.589569,Phase Fatale - Anubis - 01 Hollow Flesh_pn,NØXIA - Pray For Me_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...
1295.673469,Phase Fatale - Anubis - 01 Hollow Flesh_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...,ALTIMAIT - Underwater_pn
1304.961451,Phase Fatale - Anubis - 01 Hollow Flesh_pn,ALTIMAIT - Underwater_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...
1332.825397,She Lost Kontrol - Surviving In Europe - 13 Pr...,Phase Fatale - Anubis - 01 Hollow Flesh_pn,ALTIMAIT - Underwater_pn
1337.469388,She Lost Kontrol - Surviving In Europe - 13 Pr...,ALTIMAIT - Underwater_pn,Phase Fatale - Anubis - 01 Hollow Flesh_pn
1342.113379,She Lost Kontrol - Surviving In Europe - 13 Pr...,ALTIMAIT - Underwater_pn,Madonna - Holy Water [Allan Natal Remix J. Lem...
1346.757370,She Lost Kontrol - Surviving In Europe - 13 Pr...,Madonna - Holy Water [Allan Natal Remix J. Lem...,ALTIMAIT - Underwater_pn
1402.485261,She Lost Kontrol - Surviving In Europe - 13 Pr...,Madonna - Holy Water [Allan Natal Remix J. Lem...,NØXIA - Lemon Pie_pn
1476.789116,She Lost Kontrol - Surviving In Europe - 13 Pr...,Madonna - Holy Water [Allan Natal Remix J. Lem...,Billy Idol - Cyberpunk - Tomorrow People_pn
1490.721088,She Lost Kontrol - Surviving In Europe - 13 Pr...,Billy Idol - Cyberpunk - Tomorrow People_pn,Alessandro Adriani - Fall Elsewhere and Shatte...
1495.365079,Alessandro Adriani - Fall Elsewhere and Shatte...,She Lost Kontrol - Surviving In Europe - 13 Pr...,Billy Idol - Cyberpunk - Tomorrow People_pn
1500.009070,Alessandro Adriani - Fall Elsewhere and Shatte...,Billy Idol - Cyberpunk - Tomorrow People_pn,She Lost Kontrol - Surviving In Europe - 13 Pr...
1509.297052,Alessandro Adriani - Fall Elsewhere and Shatte...,Billy Idol - Cyberpunk - Tomorrow People_pn,Suicide Commando - X.20 - Remixes - Menschenfr...
1565.024943,Alessandro Adriani - Fall Elsewhere and Shatte...,Suicide Commando - X.20 - Remixes - Menschenfr...,Billy Idol - Cyberpunk - Tomorrow People_pn
1620.752834,Alessandro Adriani - Fall Elsewhere and Shatte...,Suicide Commando - X.20 - Remixes - Menschenfr...,6034323_Down There With You_(Original Mix)_PN
1639.328798,Alessandro Adriani - Fall Elsewhere and Shatte...,6034323_Down There With You_(Original Mix)_PN,Suicide Commando - X.20 - Remixes - Menschenfr...
1657.904762,6034323_Down There With You_(Original Mix)_PN,Alessandro Adriani - Fall Elsewhere and Shatte...,Suicide Commando - X.20 - Remixes - Menschenfr...
1662.548753,6034327_United _94_(Original Mix)_PN,6034323_Down There With You_(Original Mix)_PN,Suicide Commando - X.20 - Remixes - Menschenfr...
1681.124717,6034327_United _94_(Original Mix)_PN,6034323_Down There With You_(Original Mix)_PN,6034318_First Reprisal_(Original Mix)_PN
1685.768707,6034327_United _94_(Original Mix)_PN,14185526_Coming Down (Butchered)_(Original Mix...,6034318_First Reprisal_(Original Mix)_PN
1690.412698,6034327_United _94_(Original Mix)_PN,14185526_Coming Down (Butchered)_(Original Mix...,1255159_Policy Of Truth_(Capitol Mix)_pn
1695.056689,14185526_Coming Down (Butchered)_(Original Mix...,6034327_United _94_(Original Mix)_PN,1255159_Policy Of Truth_(Capitol Mix)_pn
1699.700680,14185526_Coming Down (Butchered)_(Original Mix...,6034327_United _94_(Original Mix)_PN,10 - Slip Slide Melting_pn
1727.564626,14185526_Coming Down (Butchered)_(Original Mix...,10 - Slip Slide Melting_pn,6034327_United _94_(Original Mix)_PN
1732.208617,14185526_Coming Down (Butchered)_(Original Mix...,1002070_Mirror Saw_(Dub Mix)_PN,10 - Slip Slide Melting_pn
1746.140590,14185526_Coming Down (Butchered)_(Original Mix...,1002070_Mirror Saw_(Dub Mix)_PN,03 - Undisclosed Desires (Thin White Duke Remi...
1755.428571,14185526_Coming Down (Butchered)_(Original Mix...,1002070_Mirror Saw_(Dub Mix)_PN,Billy Idol - Cyberpunk - Neuromancer_pn
1774.004535,14185526_Coming Down (Butchered)_(Original Mix...,Billy Idol - Cyberpunk - Neuromancer_pn,1002070_Mirror Saw_(Dub Mix)_PN
1787.936508,14185526_Coming Down (Butchered)_(Original Mix...,Billy Idol - Cyberpunk - Neuromancer_pn,5020207_Pro-test_(Original Mix)_PN
1917.968254,14185526_Coming Down (Butchered)_(Original Mix...,5020207_Pro-test_(Original Mix)_PN,Billy Idol - Cyberpunk - Neuromancer_pn
1922.612245,14185526_Coming Down (Butchered)_(Original Mix...,5020207_Pro-test_(Original Mix)_PN,5255770_Time Will Destroy Everything_(Original...
1927.256236,14185526_Coming Down (Butchered)_(Original Mix...,5255770_Time Will Destroy Everything_(Original...,5020207_Pro-test_(Original Mix)_PN
1945.832200,14185526_Coming Down (Butchered)_(Original Mix...,5255770_Time Will Destroy Everything_(Original...,08 - Exterminate Annihilate Destroy_PN
1950.476190,08 - Exterminate Annihilate Destroy_PN,5255770_Time Will Destroy Everything_(Original...,14185526_Coming Down (Butchered)_(Original Mix...
1955.120181,08 - Exterminate Annihilate Destroy_PN,5255770_Time Will Destroy Everything_(Original...,40 - Blue Monday (Electro Mix)_pn
1959.764172,08 - Exterminate Annihilate Destroy_PN,02 - Banshee_PN,5255770_Time Will Destroy Everything_(Original...
1969.052154,08 - Exterminate Annihilate Destroy_PN,02 - Banshee_PN,6034316_Devil Inside_(Original Mix)_PN
2010.848073,08 - Exterminate Annihilate Destroy_PN,6034316_Devil Inside_(Original Mix)_PN,02 - Banshee_PN
2029.424036,08 - Exterminate Annihilate Destroy_PN,6034316_Devil Inside_(Original Mix)_PN,09 - Cities In Dust (Extended Version)_PN
2061.931973,08 - Exterminate Annihilate Destroy_PN,6034316_Devil Inside_(Original Mix)_PN,Collide - Chasing the Ghost - White Rabbit_pn
2071.219955,08 - Exterminate Annihilate Destroy_PN,Collide - Chasing the Ghost - White Rabbit_pn,6034316_Devil Inside_(Original Mix)_PN
2085.151927,08 - Exterminate Annihilate Destroy_PN,Collide - Chasing the Ghost - White Rabbit_pn,1275705_Floorkiller_(Deaedal Remix)_pn
2089.795918,Collide - Chasing the Ghost - White Rabbit_pn,08 - Exterminate Annihilate Destroy_PN,1275705_Floorkiller_(Deaedal Remix)_pn
2099.083900,Collide - Chasing the Ghost - White Rabbit_pn,A Split Second - Another World - Electronic Bo...,1275705_Floorkiller_(Deaedal Remix)_pn
2108.371882,Collide - Chasing the Ghost - White Rabbit_pn,A Split Second - Another World - Electronic Bo...,02 - Kill Kill_pn
2122.303855,A Split Second - Another World - Electronic Bo...,Collide - Chasing the Ghost - White Rabbit_pn,02 - Kill Kill_pn
2159.455782,A Split Second - Another World - Electronic Bo...,02 - Kill Kill_pn,Collide - Chasing the Ghost - White Rabbit_pn
2229.115646,A Split Second - Another World - Electronic Bo...,02 - Kill Kill_pn,54 - Speed Of Pain_PN
2252.335601,A Split Second - Another World - Electronic Bo...,Multiple Man - New Metal - 01 Slow Code_pn,02 - Kill Kill_pn
2261.623583,Multiple Man - New Metal - 01 Slow Code_pn,A Split Second - Another World - Electronic Bo...,02 - Kill Kill_pn
2280.199546,Multiple Man - New Metal - 01 Slow Code_pn,A Split Second - Another World - Electronic Bo...,Collide - Chasing the Ghost - White Rabbit_pn
2289.487528,Multiple Man - New Metal - 01 Slow Code_pn,Collide - Chasing the Ghost - White Rabbit_pn,1002052_Shore Lined Poison_(Remix)_pn
2294.131519,Multiple Man - New Metal - 01 Slow Code_pn,1002052_Shore Lined Poison_(Remix)_pn,Collide - Chasing the Ghost - White Rabbit_pn
2303.419501,Multiple Man - New Metal - 01 Slow Code_pn,1002052_Shore Lined Poison_(Remix)_pn,Lady Napalm - Cool Black Heart - 01 Redemption...
2321.995465,Multiple Man - New Metal - 01 Slow Code_pn,1002052_Shore Lined Poison_(Remix)_pn,6034317_Glass_(Original Mix)_PN
2345.215420,Multiple Man - New Metal - 01 Slow Code_pn,6034317_Glass_(Original Mix)_PN,1002052_Shore Lined Poison_(Remix)_pn
2368.435374,Multiple Man - New Metal - 01 Slow Code_pn,6034317_Glass_(Original Mix)_PN,(Disc 2) 04 - Breaking Up The Girl (Timo Maas ...
2396.299320,Multiple Man - New Metal - 01 Slow Code_pn,01 - This S_It Will Fcuk You Up [Explicit]_PN,(Disc 2) 04 - Breaking Up The Girl (Timo Maas ...
2400.943311,01 - This S_It Will Fcuk You Up [Explicit]_PN,Multiple Man - New Metal - 01 Slow Code_pn,(Disc 2) 04 - Breaking Up The Girl (Timo Maas ...
2405.587302,01 - This S_It Will Fcuk You Up [Explicit]_PN,07 - Hole in the Sun (feat. COS & Conway) [Exp...,Multiple Man - New Metal - 01 Slow Code_pn
2410.231293,01 - This S_It Will Fcuk You Up [Explicit]_PN,07 - Hole in the Sun (feat. COS & Conway) [Exp...,(Disc 2) 04 - Breaking Up The Girl (Timo Maas ...
2419.519274,01 - This S_It Will Fcuk You Up [Explicit]_PN,07 - Hole in the Sun (feat. COS & Conway) [Exp...,09 - Cities In Dust (Extended Version)_PN
2424.163265,01 - This S_It Will Fcuk You Up [Explicit]_PN,07 - Hole in the Sun (feat. COS & Conway) [Exp...,34 - Terrible Lie_PN
2428.807256,01 - This S_It Will Fcuk You Up [Explicit]_PN,Muse - The Resistance - MK Ultra_pn,34 - Terrible Lie_PN
2438.095238,01 - This S_It Will Fcuk You Up [Explicit]_PN,Muse - The Resistance - MK Ultra_pn,40 - Blue Monday (Electro Mix)_pn
2484.535147,01 - This S_It Will Fcuk You Up [Explicit]_PN,40 - Blue Monday (Electro Mix)_pn,Muse - The Resistance - MK Ultra_pn
2489.179138,01 - This S_It Will Fcuk You Up [Explicit]_PN,40 - Blue Monday (Electro Mix)_pn,02 - Compliance (Purple Disco Machine Remix) [...
2498.467120,01 - This S_It Will Fcuk You Up [Explicit]_PN,02 - Compliance (Purple Disco Machine Remix) [...,40 - Blue Monday (Electro Mix)_pn
2521.687075,02 - Compliance (Purple Disco Machine Remix) [...,01 - This S_It Will Fcuk You Up [Explicit]_PN,40 - Blue Monday (Electro Mix)_pn
2530.975057,02 - Compliance (Purple Disco Machine Remix) [...,40 - Blue Monday (Electro Mix)_pn,01 - This S_It Will Fcuk You Up [Explicit]_PN
2540.263039,02 - Compliance (Purple Disco Machine Remix) [...,40 - Blue Monday (Electro Mix)_pn,Muse - The Resistance - MK Ultra_pn
2544.907029,02 - Compliance (Purple Disco Machine Remix) [...,40 - Blue Monday (Electro Mix)_pn,Detriti Records - Visitor - E.B.E. - 04 Mechan...